project:
  type: website
  output-dir: docs

website:
  title: "Thomas Goodge"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

format:
  html:
    theme:
      - spacelab
      - brand
    css: styles.css
    toc: true

editor: visual

